import { type NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import { WalletSelectorContextProvider } from "../contexts/WalletSelectorContext";
import Content from "../components/Content";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WalletSelectorContextProvider>
        <Header />
        <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
          <h1>NEAR Guest Book</h1>

          <Content />
        </main>
      </WalletSelectorContextProvider>
    </>
  );
};

export default Home;
